#!/bin/bash

# Define an array of file names
files=(
  "SRR6660738"
  "SRR6660748"
  "SRR6660754"
  "SRR6660764"
  "SRR6660767"
  "SRR6660768"
  "SRR6660772"
  "SRR6660777"
)

# Loop through the files
for file in "${files[@]}"; do
  # Set the output file paths
  output_file_1="${file}_1_trim.fastq"
  output_file_2="${file}_2_trim.fastq"
#Run fastqc for quality check of trimmed sequence
  fastqc --threads 40 --outdir SRA_QC "${output_file_1}" "${output_file_2}"
done
