#!/bin/bash

# Loop through the files
for i in `cat array_srr`
do
  # Set the input and output file paths
  input_file_1="${i}_1_trim.fastq_1P"
  output_file="${i}_hisat"
  input_file_2="${i}_2_trim.fastq_2P"
  
  # Run HISAT2 for paired end putting both files and common output in SAM format will get generate
  hisat2 -x genome -1 "${input_file_1}" -2 "{input_file_2}" -S "${output_file}".sam
done

